name: Meltano CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-pipelines:
    name: Testing the Pipelines
    runs-on: ubuntu-latest
    env:
      OKTA_AUTH_TOKEN: ${{ secrets.OKTA_AUTH_TOKEN }}
      TARGET_SNOWFLAKE_USER: ${{ secrets.TARGET_SNOWFLAKE_USER }}
      TARGET_SNOWFLAKE_PASSWORD: ${{ secrets.TARGET_SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      AWS_ID: ${{ secrets.AWS_ID }}
      AWS_PSW: ${{ secrets.AWS_PSW }}
      CVENT_OAUTH_KEY: ${{ secrets.CVENT_OAUTH_KEY }}
      TAP_GA4_PROPERTY_ID: ${{ secrets.TAP_GA4_PROPERTY_ID }}
      TAP_GA4_CLIENT_SECRETS: ${{ secrets.TAP_GA4_CLIENT_SECRETS }}
      
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installing Dependencies
        run: |
          pip install meltano==2.19.1
          pip install -r requirements.txt

      # Testing if every pipeline is working as expected
      - name: Testing OKTA Pipeline
        run: |
          export START_DATE_TAPOKTA_DEV=$(date +%Y-%m-%d -d '1 day ago')
          meltano --environment=dev run okta-pipeline
      - name: Testing TOTANGO Pipeline
        run: |
          meltano --environment=dev run totango-pipeline--accounts
          meltano --environment=dev run totango-pipeline--events
          meltano --environment=dev run totango-pipeline--users
          meltano --environment=dev run totango-pipeline--touchpoint_types
          meltano --environment=dev run totango-pipeline--touchpoint_tags
          meltano --environment=dev run totango-pipeline--touchpoints
      - name: Testing GA4 Pipeline
        run: |
          export START_DATE_TAPGA4_DEV=$(date +%Y-%m-%d -d '1 day ago')
          meltano --environment=dev run google-analytics-pipeline--web_traffic
          meltano --environment=dev run google-analytics-pipeline--page_path
      - name: Testing CVENT Pipeline
        run: |
          meltano --environment=dev run events-pipeline

  build-docker-image:
    name: Building Docker Image
    runs-on: ubuntu-latest
    needs: test-pipelines

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  
      # Building docker image
      - name: Build Docker Image
        run: |
          docker build -t meltano_test .
        
